const langs = {
  "en-US": {
    "menu.title": "Idle Taco 2",
    "menu.startBtn": "Start",
    "menu.optionsBtn": "Options",
    "menu.creditsBtn": "Credits",
    "menu.version": "Version: ",
    "menu.copy": "&copy;2022 Noob Killa Studios",
    "options.title": "Options",
    "options.music": "Toggle Music",
    "options.langLabel": "Language: ",
    "options.lang.en-US": "English (US)",
    "options.lang.es-ES": "Epañol",
    "options.lang.dev": "dev",
    "generic.back": "Back",
    "credits.title": "Credits",
    "credits.originalIdea": "Original Idea: Egg Egg Egg Studio",
    "credits.mainDesign": "Main Design: Noob Killa Studios and Ojas Bhat",
    "credits.music": "Music:",
    "credits.code": "Code: Noob Killa Studios",
    "credits.assets": "Assets: Egg Egg Egg Studio"
  },
  "es-ES": {
    "menu.title": "Taco inactivo 2",
    "menu.startBtn": "Comienzo",
    "menu.optionsBtn": "Opciones",
    "menu.creditsBtn": "Créditos",
    "menu.version": "Version: ",
    "menu.copy": "&copy;2022 Noob Killa Studios",
    "options.title": "Opciones",
    "options.music": "Alternar música",
    "options.langLabel": "Idioma: ",
    "options.lang.en-US": "English (US)",
    "options.lang.es-ES": "Epañol",
    "options.lang.dev": "dev",
    "generic.back": "Atrás",
    "credits.title": "Créditos",
    "credits.originalIdea": "Idea original: Egg Egg Egg Studio",
    "credits.mainDesign": "Diseño principal: Noob Killa Studios and Ojas Bhat",
    "credits.music": "Música:",
    "credits.code": "Código: Noob Killa Studios",
    "credits.assets": "Activos: Egg Egg Egg Studio"
  }
};